"""
build_quarto.py — Turn the generated Product 1 pages into a Quarto website (folder site/),
rendered and published to GitHub Pages by .github/workflows/publish-site.yml.

Why a converter and not hand-written .qmd: the summary and the fact sheets are generated by
product1_summary.py and product1_factsheets.py from the data tables. This script only wraps
that generated HTML in Quarto pages, so Quarto supplies the navigation bar, the site search,
the footer and a common look, while every number still comes from the generators.

Output (versioned; GitHub Actions renders it, no data or Python needed there):
  site/_quarto.yml        site configuration (navbar, footer, theme, no indexing by search engines)
  site/index.qmd          home page: what the site is, how to read it, authorship
  site/sumario.qmd        executive summary
  site/fichas.qmd         table of all areas with a text filter
  site/fichas/<unit>.qmd  one page per area (change map embedded)
  site/robots.txt         asks search engines not to index the site
  site/styles.css         small site-wide adjustments

Run from the repository root, after:
  python scripts/analysis/product1_factsheets.py --units all
  python scripts/analysis/product1_summary.py
then:
  python scripts/analysis/build_quarto.py
  quarto render site            # optional local preview; output in site/_site (not versioned)

What can break, and how you would notice:
  - The generators change their HTML structure (<main>, <style>, nav.topnav): the script
    stops with "structure not found" naming the file.
  - CSS of the generated pages leaking into the Quarto theme: each page's CSS is scoped to
    a wrapper class (.ap-ficha, .ap-sum, .ap-idx) by scope_css(); a rule the scoper cannot
    parse is kept unscoped and printed as a warning.
"""
import re
import shutil
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
P1 = ROOT / "data/derived/product1"
SITE = ROOT / "site"
AUTHORS = "Mario Barroso Ramos Neto e Claude (Anthropic)"
TITLE = "Áreas Prioritárias Cerrado–Pantanal"


def scope_css(css: str, scope: str) -> str:
    """Prefix every selector with `scope`, drop dark-mode blocks (the Quarto theme is light
    only), map :root/body to the scope and drop page-level rules (main, *)."""
    out, i = [], 0
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    while i < len(css):
        j = css.find("{", i)
        if j < 0:
            break
        sel = css[i:j].strip()
        if sel.startswith("@media"):
            # find the matching closing brace of the media block
            depth, k = 1, j + 1
            while depth and k < len(css):
                depth += {"{": 1, "}": -1}.get(css[k], 0); k += 1
            inner = css[j + 1:k - 1]
            if "prefers-color-scheme" not in sel:
                out.append(f"{sel}{{{scope_css(inner, scope)}}}")
            i = k
            continue
        k = css.find("}", j)
        body = css[j + 1:k]
        i = k + 1
        if "data-theme" in sel:
            continue
        parts = []
        for s in sel.split(","):
            s = s.strip()
            if s in ("main",):
                parts = None; break
            if s in (":root", "body"):
                parts.append(scope)
            elif s == "*":
                parts.append(f"{scope} *")
            else:
                parts.append(f"{scope} {s}")
        if parts:
            if scope in parts and "background" in body:
                body = re.sub(r"background:[^;]+;?", "", body)   # let the Quarto page background show
            if scope in parts:
                body = re.sub(r"font:[^;]+;?", "", body)         # use the Quarto font
                body = re.sub(r"margin:0;?", "", body)
            out.append(f"{','.join(parts)}{{{body}}}")
    return "\n".join(out)


def split_page(path: Path):
    html = path.read_text(encoding="utf-8")
    m_css = re.search(r"<style>(.*?)</style>", html, re.S)
    m_main = re.search(r"<main>(.*)</main>", html, re.S)
    if not (m_css and m_main):
        raise SystemExit(f"structure not found in {path}")
    body = re.sub(r'<nav class="topnav">.*?</nav>', "", m_main.group(1), flags=re.S)
    return m_css.group(1), body


def qmd(pagetitle: str, css: str, scope: str, body: str) -> str:
    # Raw HTML block: Quarto passes it through untouched. pagetitle sets <title> without an
    # extra title block (the generated page already has its own heading).
    return (f'---\npagetitle: "{pagetitle}"\n---\n\n```{{=html}}\n<style>\n{css}\n</style>\n'
            f'<div class="{scope[1:]}">\n{body}\n</div>\n```\n')


for f in (P1 / "fichas/index.html", P1 / "sumario_executivo.html"):
    if not f.exists():
        raise SystemExit(f"missing {f}: run the generators first (see the docstring)")

if SITE.exists():
    shutil.rmtree(SITE)
(SITE / "fichas").mkdir(parents=True)

# --- Fact sheets -------------------------------------------------------------------------------
css_f = None
n = 0
for f in sorted((P1 / "fichas").glob("ficha_*.html")):
    css, body = split_page(f)
    css_f = css_f or scope_css(css, ".ap-ficha")
    unit = f.stem.replace("ficha_", "")
    name = re.search(r"<h2>(.*?) <span", body)
    title = f"{name.group(1) if name else 'Ficha'} ({unit})"
    (SITE / "fichas" / f"{unit}.qmd").write_text(qmd(title, css_f, ".ap-ficha", body), encoding="utf-8")
    n += 1

# --- Index of fact sheets ------------------------------------------------------------------------
css, body = split_page(P1 / "fichas/index.html")
body = re.sub(r'href="ficha_([^"]+)\.html"', r'href="fichas/\1.html"', body)
body = body.replace('<h1>', '<h1 class="ap-h1">', 1)
(SITE / "fichas.qmd").write_text(qmd("Fichas por área", scope_css(css, ".ap-idx"), ".ap-idx", body), encoding="utf-8")

# --- Executive summary ----------------------------------------------------------------------------
css, body = split_page(P1 / "sumario_executivo.html")
body = body.replace('href="index.html"', 'href="fichas.html"')
(SITE / "sumario.qmd").write_text(qmd("Sumário executivo", scope_css(css, ".ap-sum"), ".ap-sum", body), encoding="utf-8")

# --- Home page ------------------------------------------------------------------------------------
(SITE / "index.qmd").write_text(f'''---
title: "{TITLE}"
subtitle: "Estado e dinâmica da vegetação natural nas Áreas Prioritárias para a Conservação, 2012–2025"
---

Este site reúne o diagnóstico do estado da vegetação natural nas **348 Áreas Prioritárias para a Conservação do Cerrado e do Pantanal** da 2ª atualização (294 áreas da camada oficial e 54 áreas híbridas) e de como ela mudou entre 2012, ano em que as áreas foram desenhadas, e 2025. A base é a Coleção 11 do MapBiomas.

O diagnóstico **descreve estado e dinâmica**. Ele não avalia a eficácia das áreas como política pública, nem inclui fogo e degradação nesta versão.

## O que há aqui

- **[Sumário executivo](sumario.qmd):** método simplificado, resultados consolidados por importância biológica, prioridade de ação, ação recomendada e UF, mapa das categorias e subsídios para o próximo ciclo de revisão.
- **[Fichas por área](fichas.qmd):** uma ficha para cada área, com estado em 2025, categoria de dinâmica, alertas, mapa de mudanças 2012–2025, trajetória anual, composição da paisagem, destino da vegetação convertida, persistência e alvos de conservação. A tabela de entrada pode ser filtrada por nome, UF, categoria, importância ou alerta.
- **Busca:** o ícone de lupa no topo procura em todas as páginas.

## Como ler as categorias

Cada área recebe uma categoria pela tendência anual da área não convertida (vegetação natural mais água e areia) entre 2012 e 2025, em % ao ano da vegetação natural de 2012: ganho líquido, estável, rotatividade, perda moderada (até −1%/ano), perda intensa (−1 a −2%/ano) e perda muito intensa (abaixo de −2%/ano). Cheias e variações de água não contam como perda. Alertas independentes indicam aceleração, baixa confiança, dinâmica hidrológica, possível reservatório, área pequena e área híbrida.

## Situação

Versão preliminar para discussão, gerada em {date.today():%d/%m/%Y}. Os números podem mudar com revisões de método ou de dados. O código, os dados derivados e o registro das decisões metodológicas estão no [repositório do projeto](https://github.com/barroso2501/Priority-Areas-Cerrado-Pantanal).

**Autoria:** {AUTHORS}.
''', encoding="utf-8")

# --- Configuration ---------------------------------------------------------------------------------
(SITE / "_quarto.yml").write_text(f'''project:
  type: website
  output-dir: _site
  resources:
    - robots.txt

lang: pt-BR

website:
  title: "{TITLE}"
  search: true
  navbar:
    left:
      - href: index.qmd
        text: Início
      - href: sumario.qmd
        text: Sumário executivo
      - href: fichas.qmd
        text: Fichas por área
    right:
      - icon: github
        href: https://github.com/barroso2501/Priority-Areas-Cerrado-Pantanal
  page-footer:
    left: "Autoria: {AUTHORS}"
    right: "Dados: MapBiomas Coleção 11; Áreas Prioritárias, 2ª atualização"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    page-layout: article
    grid:
      body-width: 960px
    include-in-header:
      text: '<meta name="robots" content="noindex, nofollow">'
''', encoding="utf-8")
(SITE / "robots.txt").write_text("User-agent: *\nDisallow: /\n", encoding="utf-8")
(SITE / "styles.css").write_text(
    "/* Site-wide adjustments; page content styles are scoped inside each page. */\n"
    ".ap-ficha .ficha{border-top:3px solid #0b0b0b}\n"
    ".ap-idx h1.ap-h1,.ap-sum h1{font-size:1.8rem;line-height:1.2}\n", encoding="utf-8")
(SITE / ".gitignore").write_text("_site/\n.quarto/\n", encoding="utf-8")
print(f"site/: {n} fact sheets + index + summary + home")
